# Generated by Django 4.2.3 on 2023-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=8)),
                ('pric', models.DecimalField(decimal_places=2, max_digits=350)),
                ('descriptio', models.TextField()),
            ],
        ),
    ]
